AllCops:
  Excludes:
    - assets/vendor/**
    - genghis.rb
    - tmp/**
    - vendor/**

Documentation:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

SpaceInsideHashLiteralBraces:
  EnforcedStyle:               no_space
  EnforcedStyleForEmptyBraces: no_space


# Let's agree to disagree...

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Encoding:
  Enabled: false

HandleExceptions:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

NumericLiterals:
  Enabled: false

RaiseArgs:
  Enabled: false
