AllCops:
  Excludes:
    - assets/vendor/**
    - genghis.rb
    - tmp/**
    - vendor/**

Documentation:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

SpaceInsideHashLiteralBraces:
  EnforcedStyle:               no_space
  EnforcedStyleForEmptyBraces: no_space