# we're exploiting the promise that there's "at least one version of Ruby available"...
language: php

php:
 - 5.4

services: mongodb

before_script:
 - 'echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
 - 'bundle install --without development'

# wheee!
script: rspec